version: '3.9'

services:
  web:
    image: "shrutidocker2024/cicddemo-app:latest"
    ports:
      - "80:80"  # Maps port 8000 on the host to port 80 in the container
    #volumes:
     # - ./html:/usr/share/nginx/html  # Mounts the local "html" directory to the container
    #restart: always  # Ensures the container restarts automatically in case of failure
